const {Router} = require("express")
const router = Router()
const {sendTestEmail,sendEmailConfirm,sendEmailWorkCanceled,sendEmailWorkConfirmed,sendNotificationForm,sendSupportEmail} = require("../controllers/email")

router.route("/")
.post(sendTestEmail)
router.route("/confirm")
.post(sendEmailConfirm)
router.route("/sendEmailWorkConfirmed")
.post(sendEmailWorkConfirmed)
router.route("/sendEmailWorkCanceled")
.post(sendEmailWorkCanceled)
router.route("/sendNotificationForm")
.post(sendNotificationForm)
router.route("/sendSupportEmail")
.post(sendSupportEmail)
module.exports = router